### ISSUE TITLE
Apacman aurtab?

### ISSUE THREAD

**Issue by uberspot** [worzel666/aurtab#1]
This is sweet! :D 
How easy would it be to also provide one for apacman? 
https://github.com/oshazard/apacman 

Lots of the switches are fairly similar (and almost identical with pacman's).

**Comment by worzel666** [comment]
Most of the yaourt completion file is taken from the zsh-completion package; I'll give it a try though.

**Comment by worzel666** [comment]
I've pushed a new completion file, could you try it out please and let me know of any changes which need to be made?

**Comment by uberspot** [comment]
I copied it to /usr/share/zsh/site-functions/_apacman (and fixed the aapacman in the file as well to -> apacman) but it doesn't seem to work. I'm not sure if i'm doing something wrong. I tried with aapacman too and made no difference.

**Comment by worzel666** [comment]
I didn't notice the aapacman error, thanks. I've updated the file in the repo; I made a really stupid mistake. Sorry, it should work now.

**Comment by uberspot** [comment]
Sweet works fine :D thank you!
